/*
	Configuration options used by platform specific code.

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#define RomFileName "vMac.ROM"
#define EnableDragDrop 1
#define EnableAltKeysMode 0
#define SwapCommandControl 0
#define WantInitMagnify 0
#define WantInitFullScreen 0
#define WantInitRunInBackground 0
#define EnableMagnify 0
#define EnableFullScreen 0 
#define NeedRequestInsertDisk 1
#define NeedDoMoreCommandsMsg 1
#define NeedDoAboutMsg 1
#define UseControlKeys 1
#define UseActvCode 0

/* version and other info to display to user */

#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-3.1.3-sl86"
#define kStrCopyrightYear "2009"
#define kMaintainerName "unknown"
#define kStrHomePage "http://minivmac.sourceforge.net/"
#define kEmuName "Plus 4M"
